"""End-to-end smoke test for the EndoMapper/COLMAP evaluation pipeline.

Real EndoMapper data isn't available yet (Synapse access pending), so this
exercises every piece of new code -- COLMAP reader, EndoMapper dataset
loader, evaluate_endomapper.py, visualize_endomapper.py -- against a small
synthetic COLMAP reconstruction (tests/make_fake_endomapper_seq.py), using
the two real SHADeS checkpoints already vendored in ckpt/ so actual model
loading + inference is exercised too (not just file parsing).

NOTE: neither vendored checkpoint's folder name contains "shadespp", so both
load as plain SHADeS (3-channel input) -- this validates the pipeline
mechanics with two independently-loaded checkpoints, not a real SHADeS vs.
SHADeS++ comparison. Once a real SHADeS++ checkpoint (folder name containing
"shadespp", trained via configs/shadespp_tau*.json) is available, point
configs/endomapper_example.json at it and the 7-channel decompose->depth
path will be used automatically.

Usage:
    python tests/test_endomapper_pipeline.py
"""
from __future__ import absolute_import, division, print_function

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

CKPT_A = "ckpt/finetuned_mono_hkfull_288_pseudo_dsms_automasking_noadjust/weights_19"
CKPT_B = "ckpt/finetuned_mono_hkfull_288_pseudo_dsms_automasking/weights_19"


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)
    print("  OK: " + msg)


def test_colmap_reader_roundtrip(seq_dir):
    from datasets import colmap_utils

    colmap_dir = os.path.join(seq_dir, "meta-data", "colmap")
    cameras, images, points3D = colmap_utils.read_model(colmap_dir)
    check(len(cameras) == 1, "reads 1 camera")
    check(len(images) > 0, "reads >0 images")
    check(len(points3D) > 0, "reads >0 3D points")

    image_id = sorted(images.keys())[len(images) // 2]
    image = images[image_id]
    camera = cameras[image.camera_id]
    pixels, depths, point3D_ids = colmap_utils.project_points_to_image(image, camera, points3D)
    check(pixels.shape[0] > 0, "reprojects >0 points for a sample frame")
    check((depths > 0).all(), "all reprojected depths are positive")

    # The freshly-computed reprojection should match the (X, Y) keypoints
    # the generator wrote into images.txt for the same points, since those
    # were generated by the identical projection.
    obs_by_id = {pid: (x, y) for x, y, pid in zip(image.xys[:, 0], image.xys[:, 1], image.point3D_ids)}
    mismatches = 0
    for (u, v), pid in zip(pixels, point3D_ids):
        ox, oy = obs_by_id[pid]
        if abs(u - ox) > 1e-3 or abs(v - oy) > 1e-3:
            mismatches += 1
    check(mismatches == 0, "reprojected pixels match the generator's recorded keypoints")


def run(cmd, cwd):
    print("  $ " + " ".join(cmd))
    proc = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if proc.returncode != 0:
        print(proc.stdout)
        raise AssertionError("command failed (exit {}): {}".format(proc.returncode, " ".join(cmd)))
    return proc.stdout


def count_csv_data_rows(path):
    with open(path) as f:
        rows = list(csv.reader(f))
    return max(len(rows) - 1, 0)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out_dir", type=str, default=None,
                         help="where to write the fake sequence + outputs (default: a temp dir)")
    parser.add_argument("--keep", action="store_true", help="don't delete out_dir on success")
    args = parser.parse_args()

    for ckpt in (CKPT_A, CKPT_B):
        if not os.path.isdir(os.path.join(REPO_ROOT, ckpt)):
            print("SKIPPING: checkpoint not found at {} -- this smoke test needs the vendored "
                  "ckpt/ checkpoints.".format(ckpt))
            return

    out_dir = args.out_dir or tempfile.mkdtemp(prefix="endomapper_smoke_")
    print("Working directory:", out_dir)

    try:
        print("\n[1/5] Generating synthetic COLMAP sequence...")
        sys.path.insert(0, os.path.join(REPO_ROOT, "tests"))
        import make_fake_endomapper_seq
        seq_name = "Seq_TEST"
        seq_dir = make_fake_endomapper_seq.generate(
            out_dir, seq_name=seq_name, n_frames=6, n_points=300, width=288, height=288)

        print("\n[2/5] Checking COLMAP reader against the generator's ground truth...")
        test_colmap_reader_roundtrip(seq_dir)

        print("\n[3/5] Writing eval config...")
        cfg = {
            "data_root": out_dir,
            "sequences": [seq_name],
            "colmap_subdir": "meta-data/colmap",
            "frames_subdir": None,
            "img_ext": None,
            "min_depth": 0.1,
            "max_depth": 150.0,
            "num_layers": 18,
            "min_points_per_frame": 5,
            "output_dir": os.path.join(out_dir, "eval_out"),
            "models": [
                {"name": "SHADeS_ckptA", "load_weights_folder": CKPT_A},
                {"name": "SHADeS_ckptB", "load_weights_folder": CKPT_B},
            ],
        }
        cfg_path = os.path.join(out_dir, "config.json")
        with open(cfg_path, "w") as f:
            json.dump(cfg, f, indent=2)

        print("\n[4/5] Running evaluate_endomapper.py end-to-end...")
        run([sys.executable, "evaluate_endomapper.py", "--config", cfg_path, "--no_cuda"], cwd=REPO_ROOT)

        import glob
        per_frame_csvs = glob.glob(os.path.join(cfg["output_dir"], "endomapper_per_frame_results_*.csv"))
        summary_csvs = glob.glob(os.path.join(cfg["output_dir"], "endomapper_summary_results_*.csv"))
        check(len(per_frame_csvs) == 1, "evaluate_endomapper.py wrote a per-frame results CSV")
        check(len(summary_csvs) == 1, "evaluate_endomapper.py wrote a summary results CSV")
        n_rows = count_csv_data_rows(per_frame_csvs[0])
        check(n_rows == 6 * 2, "per-frame CSV has one row per (frame, model) = {} rows".format(6 * 2))

        print("\n[5/5] Running visualize_endomapper.py end-to-end...")
        run([sys.executable, "visualize_endomapper.py", "--config", cfg_path, "--health_only",
             "--no_cuda"], cwd=REPO_ROOT)

        viz_out = os.path.join(out_dir, "viz_out")
        run([sys.executable, "visualize_endomapper.py", "--config", cfg_path,
             "--output_dir", viz_out, "--max_frames", "2", "--no_cuda"], cwd=REPO_ROOT)
        written = glob.glob(os.path.join(viz_out, seq_name, "*.png"))
        check(len(written) == 2, "visualize_endomapper.py wrote 2 composite PNGs")

        print("\nALL CHECKS PASSED")
    finally:
        if not args.keep:
            shutil.rmtree(out_dir, ignore_errors=True)
        else:
            print("Left outputs in", out_dir)


if __name__ == "__main__":
    main()
